### ISSUE TITLE
能提交特权码后直接跳转支付页面吗

### ISSUE THREAD

**Issue by shuiqukeyou** [q526933815/damaiTi9#11]
我傍晚也研究了一下脚本来着，但是前端底子比较拙计，就准备写爬虫直接上的，但是纯程序模拟登录比较麻烦（滑条验证，得上无头浏览器，我估计了工作量搞不完）

任何票的结算页面的URL都是这个：`https://buy.damai.cn/orderConfirm?exParams=%7B%22damai%22%3A%221%22%2C%22channel%22%3A%22damai_app%22%2C%22umpChannel%22%3A%2210002%22%2C%22atomSplit%22%3A%221%22%2C%22serviceVersion%22%3A%221.8.5%22%7D&buyParam=593089517773_2_4270412303056&buyNow=true&spm=a2oeg.project.projectinfo.dbuy`
**（注意中间靠后的那串数字“593089517773_2_4270412303056”）**

其中的“593089517773”是ti9的演出/赛事代码
![image](https://user-images.githubusercontent.com/18672635/58271852-95628c80-7dbf-11e9-91d3-1e2a0845758a.png)

2是指两张票

4270412303056是决赛票的代码
![image](https://user-images.githubusercontent.com/18672635/58270943-867ada80-7dbd-11e9-97ed-92cec4ccca02.png)
点击购买实际上就是在get这个页面

用现在能下单的票实验的话就是这样
![image](https://user-images.githubusercontent.com/18672635/58271269-4536fa80-7dbe-11e9-9345-5de9b9220cf2.png)
![image](https://user-images.githubusercontent.com/18672635/58271330-65ff5000-7dbe-11e9-87f1-17c97e9eb586.png)
![image](https://user-images.githubusercontent.com/18672635/58271381-8202f180-7dbe-11e9-8166-50949fc687e8.png)

如果改成下4张就是
![image](https://user-images.githubusercontent.com/18672635/58271560-e6be4c00-7dbe-11e9-8b8a-1d45c30293ef.png)

我知道这个现在的这个脚本点击选择票类和+号的的速度是很快的，毕竟就是直接执行点击事件，但是能不能提交完特权码直接跳转访问结算页面？哪怕能快上那么一点点

点击+号并不触发与服务器的通信，所以不会因为直接跳结算页面导致被认定是爬虫

**Comment by TinaryTree** [comment]
这种直接调api的高端操作我也不是没想过，你知道4后面那串数字怎么生成的吗？😂我也想知道。需要反编译他的js然后给函数下断点一点一点找，理论上是可以破解的，我也是前天刚想起来写，时间来不及了

**Comment by shuiqukeyou** [comment]
> 这种直接调api的高端操作我也不是没想过，你知道4后面那串数字怎么生成的吗？😂我也想知道。需要反编译他的js然后给函数下断点一点一点找，理论上是可以破解的，我也是前天刚想起来写，时间来不及了

你说的4后面的那串是指李荣浩的那个例子后面的“4283435691837”吗，这东西是固定的，是票的skuid，不是JS算出来的，出特权码的当天我就把ti的票的skuid翻到了，已经三天了并没有变过，当然不排除它当天突然变的可能性，不过我觉得很小

API做URL解码之后是这样:
`https://buy.damai.cn/orderConfirm?exParams={"damai":"1","channel":"damai_app","umpChannel":"10002","atomSplit":"1","serviceVersion":"1.8.5"}&buyParam=593089517773_2_4270412303056&buyNow=true&spm=a2oeg.project.projectinfo.dbuy`

里面没有什么明显需要算或者和时间挂钩的值

**Comment by shuiqukeyou** [comment]
对了大佬你的这个程序我改了一下跳过特权码之后用李荣浩的那个测试，结算页面不自动勾选观演人啊，我也没看出什么问题来
也不止我一个人遇到
![image](https://user-images.githubusercontent.com/18672635/58277216-c9dc4580-7dcb-11e9-80c7-d49f70d3fc06.png)

**Comment by TinaryTree** [comment]
非常感谢！我一会儿看一下skuid 怎么拼，观演人我是为了兼容万一需要勾俩人的情况那样写的，可能单人的时候会有问题

**Comment by TinaryTree** [comment]
> > 这种直接调api的高端操作我也不是没想过，你知道4后面那串数字怎么生成的吗？😂我也想知道。需要反编译他的js然后给函数下断点一点一点找，理论上是可以破解的，我也是前天刚想起来写，时间来不及了
> 
> 你说的4后面的那串是指李荣浩的那个例子后面的“4283435691837”吗，这东西是固定的，是票的skuid，不是JS算出来的，出特权码的当天我就把ti的票的skuid翻到了，已经三天了并没有变过，当然不排除它当天突然变的可能性，不过我觉得很小
> 
> API做URL解码之后是这样:
> `https://buy.damai.cn/orderConfirm?exParams={"damai":"1","channel":"damai_app","umpChannel":"10002","atomSplit":"1","serviceVersion":"1.8.5"}&buyParam=593089517773_2_4270412303056&buyNow=true&spm=a2oeg.project.projectinfo.dbuy`
> 
> 里面没有什么明显需要算或者和时间挂钩的值

我看了一下还是没法弄，因为我不知道exParams这个参数传进去的json里会不会带上特权码，如果带的话，字段名我也无法得知

**Comment by shuiqukeyou** [comment]
> 我看了一下还是没法弄，因为我不知道exParams这个参数传进去的json里会不会带上特权码，如果带的话，字段名我也无法得知

特权码我之前查了一下使用流程（以前别的演出或者比赛也有用过这个制度的），然后今天还问了客服了，特权码的使用流程是填特权码→点击提交→获得抢票权→抢票
换而言之就是特权码是用来使帐号获得抢票权的，哪怕最后没抢到，这个码也算是用了，也没法参加晚上的宇宙哥抢票，这一点我也找客服确认了
所以特权码大概率不是同步和订单信息一起提交上去的，现在页面的特权码提交是个空按钮，按了也没啥用，到时候应该会刷出来事件绑定，提交完了应该是需要等服务器的响应然后自动刷新页面
不过现在离抢票只剩几十分钟了分析这个也没啥用了

**Comment by mao13820** [comment]
你好，请问您是在哪的客服询问到了中午参加的码晚上不能使用呢，谢谢您了 @shuiqukeyou

**Comment by shuiqukeyou** [comment]
> 你好，请问您是在哪的客服询问到了中午参加的码晚上不能使用呢，谢谢您了 @shuiqukeyou

大麦的客服啊，不过我也没严格问他海外能不能用，我先是问了一个特权码给多个号用的情况，客服说可以，然后我问他如果三个号都输了这个特权码，还能不能给第四个帐号用，答曰不可以。反正如果已经抢到一次了的肯定是不能用的，因为大麦没有购物车才弄成可以用三次这种操作，宇宙哥平台是只能用一次的。下午这会儿应该是数据同步，完全大失败的可以晚上去宇宙哥平台试试还能不能用
