### ISSUE TITLE
如何选择决赛日的票？

### ISSUE THREAD

**Issue by azures** [q526933815/damaiTi9#3]
如何选择决赛日的票？ 谢谢大佬

**Comment by TinaryTree** [comment]
默认选的决赛日
>`self.driver.find_element_by_xpath('//div[@class="select_right_list"]/div[3]/span[2]').click()`

这里的div[3]的意思是选的第三个，如果想选其他的票可以改这个数字;
而且尝试购买两张
>`self.driver.find_element_by_xpath(  '//a[@class="cafe-c-input-number-handler cafe-c-input-number-handler-up"]').click()`
